#!/usr/bin/env node
/**
 * sync-config.mjs
 * ---------------
 * Generates every config-dependent file that cannot read `.env` at runtime,
 * so `.env` stays the single source of truth:
 *
 *   native/android/AppConfig.kt        Android widget: APP_ORIGIN
 *   native/ios/AppConfig.swift         iOS widget: appOrigin
 *   db/generated/daily_scheduler.sql   pg_cron job that calls <APP_URL>/api/public/prewarm
 *   supabase/config.toml               project_id derived from SUPABASE_URL
 *
 * Usage: npm run config:sync
 * Generated files (except config.toml) are gitignored.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

try {
  process.loadEnvFile(".env"); // real env vars win over the file
} catch {
  // No .env: rely on the real environment.
}

function need(name) {
  const value = process.env[name]?.trim();
  if (!value) {
    console.error(`✗ ${name} is not set. Add it to .env (see .env.example).`);
    process.exit(1);
  }
  return value;
}

function write(path, contents) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  console.log(`✓ wrote ${path}`);
}

const appUrl = need("APP_URL").replace(/\/+$/, "");
if (!/^https:\/\/[^\s"\\]+$/.test(appUrl)) {
  console.error(`✗ APP_URL must be an https:// origin without spaces or quotes (got "${appUrl}").`);
  process.exit(1);
}

write(
  "native/android/AppConfig.kt",
  `// GENERATED by \`npm run config:sync\` from APP_URL in .env. Do not edit.
package com.dailyhow.app.widget

object AppConfig {
    const val APP_ORIGIN = "${appUrl}"
}
`,
);

write(
  "native/ios/AppConfig.swift",
  `// GENERATED by \`npm run config:sync\` from APP_URL in .env. Do not edit.
let appOrigin = "${appUrl}"
`,
);

const template = readFileSync("db/templates/daily_scheduler.sql.tpl", "utf8");
write(
  "db/generated/daily_scheduler.sql",
  "-- GENERATED by `npm run config:sync` from APP_URL in .env. Do not edit.\n" +
    template
      .split("\n")
      .filter((line) => !line.startsWith("-- TEMPLATE:") && !line.startsWith("-- then run the generated"))
      .join("\n")
      .replaceAll("{{APP_URL}}", appUrl),
);

// Supabase CLI project id = the subdomain of SUPABASE_URL.
const supabaseUrl = process.env["SUPABASE_URL"]?.trim();
if (supabaseUrl) {
  const match = supabaseUrl.match(/^https:\/\/([a-z0-9]+)\.supabase\.co\/?$/i);
  if (match) {
    write("supabase/config.toml", `project_id = "${match[1]}"\n`);
  } else {
    console.warn(`! SUPABASE_URL is not a *.supabase.co URL; left supabase/config.toml unchanged.`);
  }
}

console.log("\nNext: run db/generated/daily_scheduler.sql once in the Supabase SQL editor.");
