// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseUrl, getSupabasePublishableKey } from './config';


/** Detects Supabase's newer opaque `sb_publishable_`/`sb_secret_` key formats. */
function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

/**
 * Wraps `fetch` to always attach the Supabase `apikey` header, and to strip
 * an incorrectly-set `Authorization: Bearer <anon key>` header when using
 * the newer opaque key format (which isn't a valid bearer JWT).
 */
function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


/**
 * Builds the browser/anon-key Supabase client using the URL/key resolved in
 * `./config` (from `.env`). Browser client uses ONLY the public anon key. Uses `localStorage` for session
 * persistence when running in the browser (undefined during SSR).
 */
function createSupabaseClient() {
  const SUPABASE_URL = getSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY = getSupabasePublishableKey();
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set them in .env (see .env.example).`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }


  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

/**
 * The app-wide Supabase client for use in browser/shared code (auth,
 * anon-key/RLS-scoped queries). Lazily instantiated on first property
 * access via a Proxy so importing this module has no side effects until
 * it's actually used. This is the client used by route components (e.g.
 * sign-in, auth state listeners) — for privileged server-only queries that
 * bypass RLS, use `client.server.ts`'s `supabaseAdmin` instead.
 *
 * Import the supabase client like this:
 * import { supabase } from "@/integrations/supabase/client";
 */
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

